# Generated by Django 5.2.17 on 2026-09-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="browser_import_done",
            field=models.BooleanField(default=False),
        ),
    ]
