# Generated by Django 5.2.17 on 2026-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_path", models.CharField(max_length=300, unique=True)),
                ("new_path", models.CharField(max_length=300)),
            ],
        ),
    ]
