# Generated by Django 5.2.17 on 2026-09-26 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        help_text="Stable id from the source, e.g. ugc-mcq-1-01",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("single", "single choice"),
                            ("multiple", "multiple choice"),
                            ("numeric", "numeric"),
                            ("assertion", "assertion-reason"),
                            ("match", "match"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("stem_html", models.TextField()),
                ("solution_html", models.TextField(blank=True)),
                ("answer_text", models.CharField(blank=True, max_length=200)),
                (
                    "tolerance",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("difficulty", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(max_length=200)),
                ("source_ref", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("reviewed", "reviewed"),
                            ("published", "published"),
                            ("flagged", "flagged"),
                            ("retired", "retired"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("flag_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("recompute_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.PositiveIntegerField(default=0)),
                ("difficulty", models.FloatField(null=True)),
                ("point_biserial", models.FloatField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="assessments.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_questions", models.PositiveSmallIntegerField(default=10)),
                (
                    "pass_mark",
                    models.PositiveSmallIntegerField(default=70, help_text="Percent"),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_test",
                        to="study.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("unit_test", "unit test"), ("paper", "paper")],
                        max_length=10,
                    ),
                ),
                ("mode", models.CharField(blank=True, max_length=10)),
                ("seed", models.BigIntegerField()),
                ("question_uids", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit_test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.unittest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=4)),
                ("text_html", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "label"), name="uniq_choice_label"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_links",
                        to="assessments.question",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_links",
                        to="study.unit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "unit"), name="uniq_question_unit"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.JSONField(blank=True, null=True)),
                ("correct", models.BooleanField(null=True)),
                ("seconds", models.PositiveIntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessments.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "question"), name="uniq_response"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "unit_test"), ("unit_test__isnull", False)),
                    models.Q(("kind", "paper"), ("unit_test__isnull", True)),
                    _connector="OR",
                ),
                name="attempt_kind_matches_target",
            ),
        ),
    ]
