# Generated by Django 5.2.17 on 2026-09-27 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("", "option"), ("left", "left"), ("right", "right")],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submitted_at__isnull", True)),
                fields=("user", "unit_test"),
                name="one_open_attempt_per_test",
            ),
        ),
    ]
