# Generated by Django 5.2.17 on 2026-09-29 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_bank_and_open_attempts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewQuestion",
            fields=[],
            options={
                "verbose_name": "question in the review queue",
                "verbose_name_plural": "questions in the review queue",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("assessments.question",),
        ),
        migrations.AlterModelOptions(
            name="itemstats",
            options={"verbose_name_plural": "item statistics"},
        ),
        migrations.AddField(
            model_name="itemstats",
            name="cleared_at_n",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="QuestionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=30)),
                ("from_status", models.CharField(blank=True, max_length=10)),
                ("to_status", models.CharField(blank=True, max_length=10)),
                ("note", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="assessments.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["question", "at", "pk"],
            },
        ),
    ]
