# Generated by Django 5.2.17 on 2026-09-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("examinations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolvedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("held_on", models.DateField(blank=True, null=True)),
                (
                    "page_path",
                    models.CharField(
                        help_text="The solved page, e.g. exams/appsc/solved-2025-paper-ii.html",
                        max_length=300,
                    ),
                ),
                ("source", models.CharField(max_length=300)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("duration_source", models.CharField(blank=True, max_length=300)),
                ("marking_scheme", models.JSONField(blank=True, null=True)),
                ("marking_source", models.CharField(blank=True, max_length=300)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solved_papers",
                        to="examinations.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_attempt",
                        to="assessments.attempt",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="papers.solvedpaper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("official_key", models.CharField(blank=True, max_length=20)),
                ("withdrawn", models.BooleanField(default=False)),
                ("withdrawn_note", models.TextField(blank=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_uses",
                        to="assessments.question",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="papers.solvedpaper",
                    ),
                ),
            ],
            options={
                "ordering": ["paper", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("paper", "number"), name="uniq_paper_number"
                    )
                ],
            },
        ),
    ]
