# Generated by Django 5.2.17 on 2026-09-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperattempt",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Exam mode, when the paper records a duration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paperattempt",
            name="not_counted",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paperattempt",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Practice mode: the question on screen"
            ),
        ),
        migrations.AddField(
            model_name="paperattempt",
            name="revealed",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Practice mode: questions whose solution was shown",
            ),
        ),
        migrations.AddField(
            model_name="paperquestion",
            name="section",
            field=models.CharField(
                blank=True,
                help_text="For the review's totals, e.g. Statistics",
                max_length=80,
            ),
        ),
    ]
