# Generated by Django 5.2.17 on 2026-09-26 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("conducting_body", models.CharField(blank=True, max_length=200)),
                ("official_source_url", models.URLField(blank=True)),
                ("source_note", models.TextField(blank=True)),
                ("hub_path", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="examinations.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExamTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examinations.exam",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_target",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyllabusItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("text", models.TextField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("deep", "deep"),
                            ("brief", "brief"),
                            ("missing", "not here"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="examinations.exam",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="examinations.exampaper",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "order"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_path", models.CharField(max_length=400)),
                (
                    "depth",
                    models.CharField(
                        choices=[("deep", "deep"), ("brief", "brief")], max_length=10
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="examinations.syllabusitem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabus_links",
                        to="study.unit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="exampaper",
            constraint=models.UniqueConstraint(
                fields=("exam", "code"), name="uniq_exam_paper"
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusitem",
            constraint=models.UniqueConstraint(
                fields=("exam", "code"), name="uniq_syllabus_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabuslink",
            constraint=models.UniqueConstraint(
                fields=("item", "target_path"), name="uniq_syllabus_link"
            ),
        ),
    ]
